---
format_version: 10
environments:
  vishnuvardhan:
    pipelines:
      - vishnuvardhan-pipeline        
pipelines:
  vishnuvardhan-pipeline:
    group: vishnu-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      vishnu-integration:
        git: git@github.com:vishnuvardhanmaari/actions.git           
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      - first-stage:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            deployment:
              timeout: 0
              resources:
                - cds-uat
              tasks:
                - exec:
                    arguments:
                      - -c
                      - " ls &&  curl ifconfig.me "
                    command: /bin/bash
                - exec:
                    arguments:
                      - -c 
                      - pwd
                    command: /bin/bash 
                    run_if: failed
                      
